# Generated by Django 2.2.7 on 2020-11-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=36)),
                ('owner_username', models.CharField(max_length=36)),
                ('owner_password', models.CharField(max_length=36)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_contact', models.CharField(max_length=36)),
            ],
        ),
    ]
