# Generated by Django 2.2.7 on 2020-11-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=36)),
                ('admin_username', models.CharField(max_length=36)),
                ('admin_password', models.CharField(max_length=36)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_contact', models.CharField(max_length=36)),
            ],
        ),
    ]
